### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by ernany** [jlmadurga/listenclosely#1]
very good idea.
I would love to contribute to the project but could not run the demo.
I ran the demo and celery.

You can spend a tutorial to see the operation and understand the project.

**Comment by ernany** [comment]
[2016-03-11 21:04:04,478: WARNING/MainProcess] /root/listenclosely/local/lib/python2.7/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2016-03-11 21:04:04,479: WARNING/MainProcess] celery@debian ready.
[2016-03-11 21:04:04,988: WARNING/MainProcess] Traceback (most recent call last):
[2016-03-11 21:04:04,989: WARNING/MainProcess] File "/root/listenclosely/local/lib/python2.7/site-packages/yowsup_celery/stack.py", line 68, in asynloop
[2016-03-11 21:04:04,991: WARNING/MainProcess] asyncore.loop(timeout)
[2016-03-11 21:04:04,991: WARNING/MainProcess] File "/usr/lib/python2.7/asyncore.py", line 216, in loop
[2016-03-11 21:04:04,992: WARNING/MainProcess] poll_fun(timeout, map)
[2016-03-11 21:04:04,993: WARNING/MainProcess] File "/usr/lib/python2.7/asyncore.py", line 156, in poll
[2016-03-11 21:04:04,994: WARNING/MainProcess] read(obj)
[2016-03-11 21:04:04,994: WARNING/MainProcess] File "/usr/lib/python2.7/asyncore.py", line 87, in read
[2016-03-11 21:04:04,995: WARNING/MainProcess] obj.handle_error()
[2016-03-11 21:04:04,996: WARNING/MainProcess] File "/usr/lib/python2.7/asyncore.py", line 83, in read
[2016-03-11 21:04:04,996: WARNING/MainProcess] obj.handle_read_event()
[2016-03-11 21:04:04,997: WARNING/MainProcess] File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
[2016-03-11 21:04:04,998: WARNING/MainProcess] self.handle_read()
[2016-03-11 21:04:04,998: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/network/layer.py", line 88, in handle_read
[2016-03-11 21:04:04,999: WARNING/MainProcess] self.receive(data)
[2016-03-11 21:04:05,000: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/network/layer.py", line 96, in receive
[2016-03-11 21:04:05,001: WARNING/MainProcess] self.toUpper(data)
[2016-03-11 21:04:05,001: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/**init**.py", line 75, in toUpper
[2016-03-11 21:04:05,002: WARNING/MainProcess] self.**upper.receive(data)
[2016-03-11 21:04:05,003: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
[2016-03-11 21:04:05,004: WARNING/MainProcess] self.processReceived()
[2016-03-11 21:04:05,005: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
[2016-03-11 21:04:05,005: WARNING/MainProcess] self.toUpper(oneMessageData)
[2016-03-11 21:04:05,006: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
[2016-03-11 21:04:05,007: WARNING/MainProcess] self.**upper.receive(data)
[2016-03-11 21:04:05,007: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
[2016-03-11 21:04:05,008: WARNING/MainProcess] self.toUpper(payload)
[2016-03-11 21:04:05,008: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
[2016-03-11 21:04:05,009: WARNING/MainProcess] self.**upper.receive(data)
[2016-03-11 21:04:05,010: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
[2016-03-11 21:04:05,011: WARNING/MainProcess] self.toUpper(node)
[2016-03-11 21:04:05,011: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
[2016-03-11 21:04:05,012: WARNING/MainProcess] self.**upper.receive(data)
[2016-03-11 21:04:05,012: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
[2016-03-11 21:04:05,013: WARNING/MainProcess] self.toUpper(data)
[2016-03-11 21:04:05,014: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
[2016-03-11 21:04:05,015: WARNING/MainProcess] self.**upper.receive(data)
[2016-03-11 21:04:05,015: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/axolotl/layer.py", line 123, in receive
[2016-03-11 21:04:05,017: WARNING/MainProcess] self.onMessage(protocolTreeNode)
[2016-03-11 21:04:05,018: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/axolotl/layer.py", line 147, in onMessage
[2016-03-11 21:04:05,019: WARNING/MainProcess] self.toUpper(protocolTreeNode)
[2016-03-11 21:04:05,020: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/__init**.py", line 75, in toUpper
[2016-03-11 21:04:05,021: WARNING/MainProcess] self.**upper.receive(data)
[2016-03-11 21:04:05,021: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/__init**.py", line 188, in receive
[2016-03-11 21:04:05,021: WARNING/MainProcess] s.receive(data)
[2016-03-11 21:04:05,021: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/**init**.py", line 124, in receive
[2016-03-11 21:04:05,021: WARNING/MainProcess] recv(node)
[2016-03-11 21:04:05,022: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
[2016-03-11 21:04:05,022: WARNING/MainProcess] self.toUpper(entity)
[2016-03-11 21:04:05,022: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/**init**.py", line 75, in toUpper
[2016-03-11 21:04:05,022: WARNING/MainProcess] self.**upper.receive(data)
[2016-03-11 21:04:05,022: WARNING/MainProcess] File "/root/listenclosely/src/yowsup/yowsup/layers/interface/interface.py", line 100, in receive
[2016-03-11 21:04:05,023: WARNING/MainProcess] self.entity_callbacks[entityType](entity)
[2016-03-11 21:04:05,023: WARNING/MainProcess] File "/root/listenclosely/local/lib/python2.7/site-packages/listenclosely_whatsapp/layer.py", line 19, in on_message
[2016-03-11 21:04:05,023: WARNING/MainProcess] stack.caller.on_message(message_protocol_entity.getFrom(), message_protocol_entity.getBody())
[2016-03-11 21:04:05,023: WARNING/MainProcess] TypeError: on_message() takes exactly 4 arguments (3 given)
[2016-03-11 21:04:05,023: ERROR/MainProcess] Unexpected error <type 'exceptions.TypeError'>
[2016-03-11 21:04:05,025: ERROR/MainProcess] Task listenclosely.tasks.listen[590e779d-e32f-4442-9879-ba3823dfa472] raised unexpected: UnexpectedError("<type 'exceptions.TypeError'>",)
Traceback (most recent call last):
  File "/root/listenclosely/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/root/listenclosely/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call**
    return self.run(_args, *_kwargs)
  File "/root/listenclosely/local/lib/python2.7/site-packages/listenclosely/tasks.py", line 29, in listen
    return self.facade.listen()
  File "/root/listenclosely/local/lib/python2.7/site-packages/listenclosely/app.py", line 25, in listen
    self.service_backend.listen()
  File "/root/listenclosely/local/lib/python2.7/site-packages/listenclosely_whatsapp/service.py", line 48, in listen
    raise listenclosely_exceptions.UnexpectedError(str(e))
UnexpectedError: <type 'exceptions.TypeError'>

**Comment by jlmadurga** [comment]
Hi there is a bug in whatsapp backend. I will fix it there ok! https://github.com/jlmadurga/listenclosely-whatsapp/issues/2

**Comment by jlmadurga** [comment]
Try with new versions:
listenclosely==0.1.2
listenclosely-whahstapp==0.1.1

**Comment by ernany** [comment]
It worked

**Comment by jlmadurga** [comment]
Thx for your collaboration!
